config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "projects#index"
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    # require title and description
    validates_presence_of :title, :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit create destroy]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

  <html>
    <head>
      <title>Cs3300</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
      <div class="navbar navbar-expand-sm bg-dark fixed-top">
        <% if user_signed_in? %>
          <ul class="btn-group navbar-nav">
            <a class="text-white btn btn-info" <%= link_to "Home", projects_path %></a>
            <a class="text-white btn btn-info" <%= link_to 'Edit profile', edit_user_registration_path %></a>
            <a class="text-white btn btn-info" <%= link_to "Logout", destroy_user_session_path, method: :delete %></a>
          </ul>
          <span class="navbar-text" style="padding-left:20px"><strong style="color:white"><%= current_user.email %></strong>.</span>

        <% else %>
          <ul class="btn-group navbar-nav">
            <a class="text-white btn btn-info" <%= link_to "Home", projects_path %></a>
            <a class="text-white btn btn-info" <%= link_to "Sign up", new_user_registration_path %></a>
            <a class="text-white btn btn-info"<%= link_to "Login", new_user_session_path %></a>
          </ul>
        <% end %>
      </div>
      <div style="padding-top:60px"></div>
      <%= yield %>
    </body>
  </html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field text-center">
    <p style="font-size:large"><%= form.label :title %>:</p>
    <%= form.text_field :title %>
  </div>

  <br>

  <div class="field text-center">
    <p style="font-size:large"><%= form.label :description %>:</p>
    <p><%= form.text_area :description %></p>
  </div>

  <div class="actions text-center container">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div>
    <p class="container bg-primary my-3 p-3">
        <strong class="text-white" style="font-size:large">Editing Project:</strong>
        <span class="text-white" style="padding:20px"><%= @project.title %></span>
    </p>
    <%= render 'form', project: @project %>

    <div class="container">
        <a class="btn btn-warning text-white"<%= link_to 'Show', @project %></a>
        <a class="btn btn-primary text-white"<%= link_to 'Back', projects_path %></a>
    </div>
</div>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<div class="text-center">
  <%= image_tag "projects.png", style: "height:20vw;margin-bottom:20px" %>
</div>

<div class="container text-center text-info font-weight-bold" style="font-size:large;padding:50px">
  Table of Projects:
</div>

<table class="table table-striped table-bordered">
  <thead>
    <tr class="text-center">
      <th>Title</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td>
          <a class="btn btn-primary text-white" <%= link_to 'Show', project %>
        </td>
        <td>
          <a class="btn btn-warning text-white" <%= link_to 'Edit', edit_project_path(project) %>
        </td>
        <td>
          <a class="btn btn-danger text-white" <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<span class="container" style="padding-bottom:50px"><a href="projects/new" class="btn btn-success text-white">New Project</a></span>

app/views/projects/new.html.erb
<div>    
    <p class="container bg-primary my-3 p-3 text-center">
        <strong class="text-white" style="font-size:large">New Project</strong>
    </p>

    <%= render 'form', project: @project %>

    <div class="container">
        <a class="btn btn-primary text-white"<%= link_to 'Back', projects_path %></a>
    </div>
</div>

app/views/projects/show.html.erb
<div class="">
  <p id="notice"><%= notice %></p>

  <p class="container bg-primary my-3 p-3">
    <strong class="text-white" style="font-size:large">Project Title:</strong>
    <span class="text-white" style="padding:20px"><%= @project.title %></span>
  </p>

  <p class="container border my-3 p-3">
    <strong style="font-size:large">Description:</strong>
    <span style="padding:20px"><%= @project.description %></span>
  </p>

  <div class="container">
    <a class="btn btn-warning text-white"<%= link_to 'Edit', edit_project_path(@project) %></a>
    <a class="btn btn-primary text-white"<%= link_to 'Back', projects_path %></a>
  </div>
</div>